export const IS_CONNECTED = 'IS_CONNECTED';
export const SET_SAME_CLIENTS_CONNECTION = 'SET_SAME_CLIENTS_CONNECTION';
export const IS_DISCONNECTED = 'IS_DISCONNECTED';
export const SET_SOCKET_ID = 'SET_SOCKET_ID';
