export const REQUEST_SENDING_DATA = 'REQUEST_SENDING_DATA';
export const UPDATE_LOCAL_DATA = 'UPDATE_LOCAL_DATA';
export const UPDATE_UPLOAD_DATA = 'UPDATE_UPLOAD_DATA';
export const FAILURE_RECEIVE_TRANSFER = 'FAILURE_RECEIVE_TRANSFER';
