export const REQUEST_USER_DATA = 'REQUEST_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const FAILURE_RECEIVE_USER = 'FAILURE_RECEIVE_USER';
export const RESET_DATA = 'FAILURE_RECEIVE_USERESET_DATA';
